# CVE-2019-19781

Python CVE-2019-19781 exploit

| Infos    | Value                                                              |
| -------- | -------------------------------------------------------------------|
| Username | [https://github.com/r4ulcl](https://github.com/r4ulcl) |
| Url      | [https://github.com/r4ulcl/CVE-2019-19781](https://github.com/r4ulcl/CVE-2019-19781)                                               |
| Stars    | 1                                                          |
| License  | GNU General Public License v3.0                                                        |

<details>

<summary>Topic / Tags</summary>

* citrix* citrix-adc* cve-2019-19781* exploit* python3

</details>

## Readme

# CVE-2019-19781
Just a python3 CVE-2019-19781 exploit for Citrix behind a cache. This version accepts '<', '>', '|', '2>&1'... etc 

## USAGE
python3 CVE-2019-19781.py citrix.example.org 'cat /etc/passwd'

## Todo

* [X] Repeat if Age header in response.

* [ ] Continuous mode -c. 

* [ ] Check mode (Get /vpn/../vpns/cfg/smb.conf)



## Get the content

```
git clone https://github.com/r4ulcl/CVE-2019-19781
cd CVE-2019-19781
```

{% embed url="https://github.com/r4ulcl/CVE-2019-19781" %}

<figure><img src="https://avatars.githubusercontent.com/u/25440046?v=4" alt=""><figcaption><p>r4ulcl</p></figcaption></figure>
