# CVE-2016-8863

CTFs are fun, but what about exploiting a real bug?

| Infos    | Value                                                              |
| -------- | -------------------------------------------------------------------|
| Username | [https://github.com/mephi42](https://github.com/mephi42) |
| Url      | [https://github.com/mephi42/CVE-2016-8863](https://github.com/mephi42/CVE-2016-8863)                                               |
| Stars    | 1                                                          |
| License  | No License                                                        |

<details>

<summary>Topic / Tags</summary>



</details>

## Readme

# Targets

pupnp [release-1.6.18](https://github.com/pupnp/pupnp/tree/release-1.6.18) ...

* ... running on [i386 Ubuntu 16.04](i386-xenial).

# Fix

commit [9c099c2923ab](https://github.com/pupnp/pupnp/commit/9c099c2923ab)
("Fix out-of-bound access in create_url_list() (CVE-2016-8863)").



## Get the content

```
git clone https://github.com/mephi42/CVE-2016-8863
cd CVE-2016-8863
```

{% embed url="https://github.com/mephi42/CVE-2016-8863" %}

<figure><img src="https://avatars.githubusercontent.com/u/662616?v=4" alt=""><figcaption><p>mephi42</p></figcaption></figure>
